"""
Scenario Chain Synthesizer  – v2
---------------------------------
Each of the first 2 questions runs its own 3-step mini-arc:

  Decision 1  (initial MCQ, generated by question_synthesizer as normal)
      ↓
  Complication 1  (AI twist)
      ↓
  Decision 2  (harder follow-up)
      ↓
  Complication 2  (AI escalation)
      ↓
  Final Decision  (hardest, synthesis question)

After both chained questions complete, Q3-Q6 are normal standalone questions.

Chain state stored on session under `scenarioChain`:
  {
    rootScenario: str,
    chainCompetency: str,
    steps: [ScenarioStep],
    chainDepth: int,        # 0=just started, 1=after D1, 2=after D2, 3=after FD (complete)
    isActive: bool,
    lastComplication: str | None,
    questionNumber: int     # 1 or 2 (which assessment question this chain belongs to)
  }

CHAIN_DEPTH = 2 means: initial → complication → followup → complication → final
Total chain steps = 5 (3 decisions, 2 complications shown between them)
chainDepth tracks completed decisions: 0→1→2→3 (complete at 3)
"""

from typing import Any, Dict, List, Optional
from common import get_bedrock_client, invoke_bedrock_json, generate_question_id

BEDROCK_MODEL_ID = "anthropic.claude-3-haiku-20240307-v1:0"

# Number of DECISIONS per chain (initial + follow-ups). 3 = D1, D2, Final Decision
DECISIONS_PER_CHAIN = 3
# Which assessment question numbers get a chain (1-indexed)
CHAINED_QUESTION_NUMBERS = {1, 2}


# ------------------------------------------------------------------
# Chain lifecycle helpers
# ------------------------------------------------------------------

def should_start_chain(question_number: int, existing_chain: Optional[Dict]) -> bool:
    """Start a new chain if this question number is in CHAINED_QUESTION_NUMBERS."""
    if question_number not in CHAINED_QUESTION_NUMBERS:
        return False
    if existing_chain and existing_chain.get("isActive"):
        return False
    # Start if no chain yet, or previous chain is done
    if existing_chain and existing_chain.get("questionNumber") == question_number:
        return False  # already ran a chain for this question number
    return True


def is_chain_active(session: Dict) -> bool:
    chain = session.get("scenarioChain")
    return bool(chain and chain.get("isActive", False))


def chain_is_complete(chain: Dict) -> bool:
    return chain.get("chainDepth", 0) >= DECISIONS_PER_CHAIN


def init_chain(root_scenario: str, competency: str, question_number: int) -> Dict[str, Any]:
    return {
        "rootScenario": root_scenario,
        "chainCompetency": competency,
        "steps": [],
        "chainDepth": 0,
        "isActive": True,
        "lastComplication": None,
        "questionNumber": question_number,
    }


# ------------------------------------------------------------------
# Generate complication twist
# ------------------------------------------------------------------

def synthesize_complication(
    root_scenario: str,
    competency: str,
    role: str,
    level: str,
    steps_so_far: List[Dict],
    depth: int,
) -> str:
    """
    Generate an escalating complication.
    depth=1 → first twist (moderate stakes)
    depth=2 → second twist (high stakes, e.g. CEO involved)
    """
    client = get_bedrock_client()

    last_step = steps_so_far[-1] if steps_so_far else {}
    last_answer = last_step.get("candidateAnswer", "")
    last_question = last_step.get("questionText", "")

    stake_level = "moderate — a manager is asking for an update" if depth == 1 else \
                  "critical — the CEO and entire leadership team are now watching and the issue is spreading"

    system_prompt = (
        "You are a scenario writer for a FAANG-style interview simulator. "
        "Introduce a realistic COMPLICATION that escalates the original scenario. "
        "The complication must:\n"
        "  1. Follow naturally from the candidate's last decision.\n"
        f"  2. Raise the stakes to: {stake_level}.\n"
        "  3. Be 2-3 sentences. Pure narrative. No questions.\n"
        "Return ONLY the complication text. No JSON, no commentary."
    )

    user_prompt = (
        f"Role: {role} | Level: {level} | Competency: {competency}\n\n"
        f"Original scenario:\n{root_scenario}\n\n"
        f"Previous question:\n{last_question}\n\n"
        f"Candidate's decision:\n{last_answer}\n\n"
        "Write the complication twist."
    )

    if client is None:
        complications = [
            "While you were investigating, the situation escalated: the VP of Engineering "
            "has seen a spike in error alerts and called an emergency Slack huddle. "
            "Three more services are now reporting downstream failures linked to the same root cause.",

            "The situation has now reached critical level: the CEO has personally flagged this "
            "incident and wants a live briefing in 15 minutes. Simultaneously, a major client "
            "has noticed the issue and is threatening to escalate their contract review.",
        ]
        return complications[min(depth - 1, len(complications) - 1)]

    try:
        response = client.converse(
            modelId=BEDROCK_MODEL_ID,
            messages=[{"role": "user", "content": [{"text": f"{system_prompt}\n\n{user_prompt}"}]}],
            inferenceConfig={"maxTokens": 256, "temperature": 0.7},
        )
        return response["output"]["message"]["content"][0]["text"].strip()
    except Exception:
        return (
            "The situation has escalated: a second failure has been detected and "
            "the on-call manager is requesting an immediate status update."
        )


# ------------------------------------------------------------------
# Generate follow-up / final decision question
# ------------------------------------------------------------------

def synthesize_chain_followup(
    root_scenario: str,
    complication_text: str,
    competency: str,
    role: str,
    level: str,
    steps_so_far: List[Dict],
    depth: int,
) -> Dict[str, Any]:
    """
    depth=1 → follow-up question (harder)
    depth=2 → final decision (hardest, synthesis)
    """
    client = get_bedrock_client()

    is_final = depth >= DECISIONS_PER_CHAIN - 1
    difficulty = "hard" if not is_final else "hard"
    tone = (
        "a harder follow-up that tests adaptability under pressure"
        if not is_final else
        "a FINAL synthesis question that forces a definitive strategic call — "
        "the hardest decision of the arc. It should require weighing all prior decisions."
    )

    system_prompt = (
        "You are an AI interview scenario generator for an adaptive role-readiness simulator.\n\n"
        f"Generate {tone}.\n\n"
        "Return ONLY valid JSON:\n"
        "{\n"
        '  "id": "chain_q",\n'
        '  "type": "scenario_mcq",\n'
        '  "competency": "string",\n'
        '  "scenario": "2-3 sentences recapping current state",\n'
        '  "question": "the decision question",\n'
        '  "options": ["A", "B", "C", "D"],\n'
        f'  "difficulty": "{difficulty}"\n'
        "}\n\n"
        "No correctAnswer field. Evaluate decision quality and judgment."
    )

    prev_summary = ""
    for s in steps_so_far[-3:]:
        prev_summary += f"- Step {s.get('stepIndex', 0)}: {s.get('candidateAnswer', '')[:80]}\n"

    user_prompt = (
        f"Role: {role} | Level: {level} | Competency: {competency}\n\n"
        f"Original scenario:\n{root_scenario}\n\n"
        f"Latest complication:\n{complication_text}\n\n"
        f"Candidate decisions so far:\n{prev_summary}\n\n"
        "Generate the question."
    )

    fallback_options_by_depth = {
        1: [
            "Implement a quick hotfix autonomously and update stakeholders in parallel",
            "Escalate to senior leadership and wait for approval before acting",
            "Roll back all recent changes immediately regardless of impact",
            "Pause and run a full root-cause analysis before touching anything",
        ],
        2: [
            "Present a clear incident report with root cause, impact, and remediation plan",
            "Implement the fix silently and hope the issue resolves before the briefing",
            "Delegate the technical fix and focus entirely on executive communication",
            "Request more time from leadership before committing to any solution",
        ],
    }

    if client is None:
        opts = fallback_options_by_depth.get(depth, fallback_options_by_depth[1])
        label = "Given everything that has escalated" if is_final else "Given the new complication"
        return {
            "id": generate_question_id(),
            "type": "scenario_mcq",
            "competency": competency,
            "scenario": f"{root_scenario} {complication_text}",
            "question": f"{label}, what is your most critical next action?",
            "options": opts,
            "difficulty": difficulty,
        }

    data = invoke_bedrock_json(client, BEDROCK_MODEL_ID, system_prompt, user_prompt)
    if not isinstance(data, dict):
        data = {}

    qid = generate_question_id()
    options = data.get("options") or []
    if len(options) < 4:
        options = (options + ["Option A", "Option B", "Option C", "Option D"])[:4]

    return {
        "id": qid,
        "type": "scenario_mcq",
        "competency": data.get("competency", competency),
        "scenario": data.get("scenario", root_scenario),
        "question": data.get("question", "What is your next action?"),
        "options": options,
        "difficulty": data.get("difficulty", difficulty),
    }


# ------------------------------------------------------------------
# Advance the chain by one step
# ------------------------------------------------------------------

def advance_chain(session: Dict, completed_step: Dict) -> Dict[str, Any]:
    """
    Called after any chain decision is answered.
    Returns:
      {
        "complicationText": str,
        "nextQuestion": dict,
        "updatedChain": dict,
        "chainComplete": bool
      }
    """
    chain = session["scenarioChain"]
    steps = list(chain.get("steps", []))
    steps.append(completed_step)

    root_scenario = chain["rootScenario"]
    competency = chain["chainCompetency"]
    role = session["role"]
    level = session["level"]
    depth = chain.get("chainDepth", 0) + 1  # depth = number of decisions completed so far

    chain_complete = depth >= DECISIONS_PER_CHAIN

    if chain_complete:
        updated_chain = {
            **chain,
            "steps": steps,
            "chainDepth": depth,
            "isActive": False,
        }
        return {
            "complicationText": None,
            "nextQuestion": None,
            "updatedChain": updated_chain,
            "chainComplete": True,
        }

    # Generate complication and next question
    complication = synthesize_complication(
        root_scenario=root_scenario,
        competency=competency,
        role=role,
        level=level,
        steps_so_far=steps,
        depth=depth,
    )

    follow_up = synthesize_chain_followup(
        root_scenario=root_scenario,
        complication_text=complication,
        competency=competency,
        role=role,
        level=level,
        steps_so_far=steps,
        depth=depth,
    )

    follow_up["questionId"] = follow_up["id"]
    follow_up["order"] = session.get("questionCount", 1)
    follow_up["chainStep"] = depth          # 1 = first follow-up, 2 = final decision
    follow_up["complicationText"] = complication

    updated_chain = {
        **chain,
        "steps": steps,
        "chainDepth": depth,
        "isActive": True,
        "lastComplication": complication,
    }

    return {
        "complicationText": complication,
        "nextQuestion": follow_up,
        "updatedChain": updated_chain,
        "chainComplete": False,
    }
